"""Sweep-validated speculative decode defaults for Aether2B.

Auto-generated by scripts/apply_best_spec_config.py — do not edit by hand.
Re-generate by running:
    python scripts/sweep_speculative.py ...
    python scripts/apply_best_spec_config.py

Last measured: 2× RTX 4090, 262144 source tokens, bf16, YaRN ×4, no draft quant.
Post-optimisation run (dequant-cache + fast-sync-path, 3 May 2026).
"""

# Sweep result: baseline 7.409 tok/s → spec 6.377 tok/s
# α=1.0000  speedup=0.8610×  draft_quant_bits=None
SPEC_DEFAULT_SELF_SPEC_LAYERS: int = 16
SPEC_DEFAULT_TEMPERATURE: float = 0.6
SPEC_DEFAULT_DRAFT_STEPS: int = 6
SPEC_DEFAULT_MIN_DRAFT_STEPS: int = 1
SPEC_DEFAULT_MAX_DRAFT_STEPS: int = 8
SPEC_DEFAULT_ADAPT_UP_THRESHOLD: float = 0.90
SPEC_DEFAULT_ADAPT_DOWN_THRESHOLD: float = 0.60
SPEC_SWEEP_BASELINE_TOK_S: float = 7.4090
SPEC_SWEEP_BEST_TOK_S: float = 6.3770
SPEC_SWEEP_BEST_ALPHA: float = 1.0000
SPEC_SWEEP_SPEEDUP: float = 0.8610
# No draft KV-cache quantisation: 4-bit quant hurt throughput by ~4% at this
# context length (dequant overhead > bandwidth saving on RTX 4090 at 262K).
SPEC_DEFAULT_DRAFT_QUANT_BITS = None
