#!/usr/bin/env python3
"""Read sweep_speculative_ranked.json and apply best config to scheduler defaults.

Usage (run after sweep completes):
    python scripts/apply_best_spec_config.py \
        --ranked-json artifacts/sweep_speculative_ranked.json \
        --dry-run        # just print what would be set
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ranked-json", default="artifacts/sweep_speculative_ranked.json")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    ranked_path = ROOT / args.ranked_json
    if not ranked_path.exists():
        print(f"[apply] Ranked JSON not found: {ranked_path}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(ranked_path.read_text())
    best = data.get("best_config")
    baseline = data.get("baseline_tok_s", 0.0)

    if not best:
        print("[apply] best_config is empty — sweep produced no results", file=sys.stderr)
        sys.exit(1)

    depth = best["depth"]
    temp = best["temperature"]
    spec_tok_s = best["spec_tok_s"]
    alpha = best["acceptance_rate"]
    speedup = best["speedup"]

    print(f"[apply] Best config: depth={depth}, temperature={temp}")
    print(f"[apply]   baseline {baseline:.2f} tok/s → spec {spec_tok_s:.2f} tok/s  α={alpha:.3f}  speedup={speedup:.3f}×")

    if speedup < 1.0:
        print(f"[apply] WARNING: best config ({speedup:.3f}×) is still slower than baseline. "
              f"Wiring it in as default but consider disabling spec in production until a faster draft is available.")

    if args.dry_run:
        print("[apply] --dry-run: no files modified")
        return

    # ---- write constants file used by scheduler ----
    constants_path = ROOT / "aether_2b" / "spec_defaults.py"
    content = f'''"""Auto-generated by scripts/apply_best_spec_config.py.  Do not edit by hand.

Best speculative decode config found by the depth × temperature grid sweep.
Re-generate by running:
    python scripts/sweep_speculative.py ...
    python scripts/apply_best_spec_config.py
"""

# Sweep result: baseline {baseline:.3f} tok/s → spec {spec_tok_s:.3f} tok/s
# α={alpha:.4f}  speedup={speedup:.4f}×
SPEC_DEFAULT_SELF_SPEC_LAYERS: int = {depth}
SPEC_DEFAULT_TEMPERATURE: float = {temp}
SPEC_DEFAULT_DRAFT_STEPS: int = 6
SPEC_DEFAULT_MIN_DRAFT_STEPS: int = 1
SPEC_DEFAULT_MAX_DRAFT_STEPS: int = 8
SPEC_DEFAULT_ADAPT_UP_THRESHOLD: float = 0.90
SPEC_DEFAULT_ADAPT_DOWN_THRESHOLD: float = 0.60
SPEC_SWEEP_BASELINE_TOK_S: float = {baseline:.4f}
SPEC_SWEEP_BEST_TOK_S: float = {spec_tok_s:.4f}
SPEC_SWEEP_BEST_ALPHA: float = {alpha:.4f}
SPEC_SWEEP_SPEEDUP: float = {speedup:.4f}
'''
    constants_path.write_text(content, encoding="utf-8")
    print(f"[apply] Wrote {constants_path}")

    # ---- also dump a human-readable summary ----
    ranked = data.get("ranked", [])
    print("\n[apply] Full ranked table (top 10):")
    print(f"  {'depth':>5}  {'temp':>5}  {'spec_tok/s':>10}  {'α':>6}  {'speedup':>8}")
    for row in ranked[:10]:
        print(f"  {row['depth']:>5}  {row['temperature']:>5.1f}  {row['spec_tok_s']:>10.3f}  {row['acceptance_rate']:>6.3f}  {row['speedup']:>8.3f}×")


if __name__ == "__main__":
    main()
